# Cross-compilation configuration for AirJedi Desktop → Raspberry Pi 5
#
# ⚠️  APPLE SILICON USERS: This configuration does NOT work on Apple Silicon Macs
#     cross-rs only publishes x86_64 container images, which require QEMU emulation
#     on ARM64 Macs, causing rustc crashes and build failures.
#
#     Instead, use the musl method documented in CROSS_COMPILE.md:
#     1. brew install filosottile/musl-cross/musl-cross
#     2. rustup target add aarch64-unknown-linux-musl
#     3. cargo build --target aarch64-unknown-linux-musl --release
#
# This configuration is for x86_64/Intel development machines only.

[build]
# Use pre-built cross-rs image for aarch64
# This image includes OpenGL/Mesa development libraries needed for egui

# Pass through environment variables for the build
[build.env]
passthrough = [
    "RUSTFLAGS",
]

[target.aarch64-unknown-linux-gnu]
# Use the default cross image (x86_64 only)
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"
